### ISSUE TITLE
Ability to list all tasks in a Queue

### ISSUE THREAD

**Issue by RicardoVaranda** [mpneuried/rsmq-worker#14]
Just wondering if this feature is available as it is not documented, if not could you please point out how this could be achieved.

**Comment by mpneuried** [comment]
Hi, 
because rsmq ist a QUEUE it makes no sense to be able to list all tasks/messages.

The only way to get all messages is to receive them all.

But you can get it the count of messages ([`rsmq.getQueueAttributes`](https://github.com/smrchy/rsmq#getqueueattributes)) and some other information directly from the internal rsmq instance with the following code:

```js
var QUEUENAME = "myqueue";

var RSMQWorker = require( "rsmq-worker" );
var worker = new RSMQWorker( QUEUENAME );

worker.queue.getQueueAttributes( {qname: QUEUENAME}, function( err, info ){
  if( err ){
    throw( err )
    return
  }
  console.log( "Message count:", info.msgs ) 
});
```
> I added a TODO #17 to short cut the `worker.queue.getQueueAttributes` to a simple `worker.info()`.

**Comment by mpneuried** [comment]
With Version 0.5.0 i added the methods `.info()` and `.size()`
