### ISSUE TITLE
Exceptions thrown in 'message' event go unnotticed

### ISSUE THREAD

**Issue by panickos** [mpneuried/rsmq-worker#3]
While using the 'message' event to process an incoming message on a worker I noticed that the worker was throwing an 'error' event on every single message but I was not getting anything in the error object.

After many hours I realized that the problem was within one of my functions processing said messages, but I couldn't realize from where since the exception thrown what getting lost.

I'm not sure if this is something you should fix or if I should just encapsulate all my code within try {} catch {} blocks.

i.e:
```javascript
inboundQueueWorker.on('message', function(message, next, msgid) {
        try {
            ...
            next();
        } catch (e) {
            next(e)
        }
    });
```
I'd be interested to hear your opinion on this.

**Comment by mpneuried** [comment]
Thanks for this information.
i will have a look into this problem.

**Comment by mpneuried** [comment]
I added some tests to check your problem.
Internally rsmq-worker wraps the message processing with a try-catch.
This is useful, because it keeps the worker running and processing messages even if a hard error was thrown.
But before version `0.3.7` a error appeared within the console/stderr-output.
Until the new `0.3.7` this log will be prevented if an `error` listener was attached or you set `alwaysLogErrors = true`.

In your case you described taht an error event was thrown, but without any content.
I couldn't reproduce this with the [2 new test cases](https://github.com/mpneuried/rsmq-worker/commit/3d27a5385bd4215dde3c1da86c038f5bcd188f83?diff=unified#diff-1dfb9d55382998bc3fc7db988828d4a9R90). Can you help me with more details?

**Comment by panickos** [comment]
I tried your tests and it is working great! Thanks!

I think I was using an older version of the code and I was not configuring it properly.
